server:
  port: 8082
  error:
    include-stacktrace: never
spring:
  data:
    mongodb:
      uri: ${ECRITIC_MONGO_URL:mongodb://root:root@localhost:27018/ecritic?authSource=admin}
      database: ecritic
    redis:
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD:af1ce60c0f7}
  kafka:
    bootstrap-servers: ${ECRITIC_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
  application:
    properties:
      jwtSecret: ${ECRITIC_JWT_SECRET:WD+pt2xPIuz8OBDUbrPzITjE3AzVdXzy9O8YVkYR55I=}
      jwtRefreshSecret: ${ECRITIC_JWT_REFRESH_SECRET:b+q0FOnXYjUUGOKOOVpz/v1EDZd8ovG/9PWF8iI9cEM=}
      jwtExpiration: ${ECRITIC_JWT_EXPIRATION:600}
      jwtRefreshExpiration: ${ECRITIC_JWT_REFRESH_EXPIRATION:604800}

clients:
  user:
    name: users-client
    url: ${ECRITIC_USER_URL:http://localhost:8081}